server:
  port: 8130 # 服务端口

spring:
  profiles:
    active: dev # 环境设置
  application:
    name: service-vod # 服务名
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # nacos服务地址
  servlet:
    multipart:
      max-file-size: 1024MB # 最大上传单个文件大小：默认1M
      max-request-size: 1024MB # 最大置总上传的数据大小 ：默认10M

aliyun:
  vod:
    keyid: LTAI5tB2vBhd4A2awk9YDtZg
    keysecret: 38bSM5pNiQQrKaAJED2r2pZncZs4R6
    templateGroupId: VOD_NO_TRANSCODE #转码模板组id
    workflowId: 3be34bbd2cc06c1a0e5fcb1ab3d4ccd8 #工作流id